name: Test

on: [push]

jobs:
  test:
    uses: snapshot-labs/actions/.github/workflows/test.yml@main
    secrets: inherit
    with:
      mysql_database_name: snapshot_relayer_test
      mysql_schema_path: ./src/schema.sql
